// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MyWeb.Models
{
    [Table("MyProductList")]
    public partial class MyProductList
    {
        [Key]
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int pid { get; set; }

        [ForeignKey(nameof(MemberId))]
        [InverseProperty("MyProductLists")]
        public virtual Member Member { get; set; }
        [ForeignKey(nameof(pid))]
        [InverseProperty(nameof(PhoneMaster.MyProductLists))]
        public virtual PhoneMaster pidNavigation { get; set; }
    }
}