// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MyWeb.Models
{
    [Table("PhoneMaster")]
    public partial class PhoneMaster
    {
        public PhoneMaster()
        {
            MyProductLists = new HashSet<MyProductList>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string PhoneType { get; set; }
        [Required]
        [StringLength(50)]
        public string Brand { get; set; }
        [Column(TypeName = "date")]
        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        [DataType(DataType.Currency)]
        public int Price { get; set; }
        [Required]
        [StringLength(50)]
        public string RunSystem { get; set; }
        [Required]
        [StringLength(50)]
        public string RunType { get; set; }
        [Required]
        [StringLength(50)]
        public string Ram { get; set; }
        [Required]
        [StringLength(50)]
        public string Rom { get; set; }
        [Required]
        [StringLength(50)]
        public string Battery { get; set; }
        [Required]
        [StringLength(50)]
        public string ScreenRes { get; set; }
        [Required]
        [StringLength(50)]
        public string BackCamRes { get; set; }
        [Required]
        [StringLength(50)]
        public string FrontCamRes { get; set; }
        [Required]
        [StringLength(50)]
        public string TransPort { get; set; }
        [Required]
        [StringLength(50)]
        public string Weight { get; set; }
        
        [StringLength(50)]
        public string Image { get; set; }

        [InverseProperty(nameof(MyProductList.pidNavigation))]
        public virtual ICollection<MyProductList> MyProductLists { get; set; }
    }
}